version: '3.7'
services:
  arangodb_db_container:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: root
    ports:
      - 8529:8529
    volumes:
      - ~/volumes/arangodb3/container:/var/lib/arangodb3    
      - ~/volumes/arangodb3/data_container:/var/lib/arangodb3-apps

volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
